100,1
1,11,"","Smokerpowder ,",0,0,"25gp"
12,13,"","Moon mote ,",0,0,"180gp"
14,15,"","Silent portal disk ,",0,0,"360gp"
16,16,"","Amber amulet of vermin(giant bee) ,",0,0,"500gp"
17,17,"","Necklace of copper dragon scales ,",0,0,"570gp"
18,18,"","Amber amulet of vermin (giant ant, queen) ,",0,0,"700gp"
19,19,"","Amber amulet of vermin (giant praying mantis) ,",0,0,"700gp"
20,20,"","Amber amulet of vermin (Huge monstrous centipede) ,",0,0,"700gp"
21,21,"","Amber amulet of vermin (Large monstrous scorpion) ,",0,0,"700gp"
22,22,"","Amber amulet of vermin (Large monstrous spider) ,",0,0,"700gp"
23,23,"","Amber amulet of vermin (giant wasp) ,",0,0,"800gp"
24,24,"","Amber amulet of vermin (giant stag beetle) ,",0,0,"1200gp"
25,26,"","Amulet of laeral's tears ,",0,0,"1200gp"
27,28,"","Bag of boulders (full) ,",0,0,"1200gp"
29,30,"","Dragon's draught (brass) ,",0,0,"1200gp"
31,32,"","Dragon's draught (white) ,",0,0,"1200gp"
33,34,"","Travel cloak. ,",0,0,"1200gp"
35,36,"","Salve of minor spell resistance ,",0,0,"1250gp"
37,38,"","Bracers of striking (base cost) ,",0,0,"1310gp"
39,40,"","Moondraught ,",0,0,"1500gp"
41,42,"","Instrument of the bards (Fochluchan Bandore) ,",0,0,"1900gp"
43,44,"","Heart of the beast ,",0,0,"2000gp"
45,46,"","Hammer of the weaponsmith ,",0,0,"2055gp"
47,48,"","Knife of the bowyer ,",0,0,"2055gp"
49,50,"","Tongs of the armorer ,",0,0,"2055gp"
51,52,"","Dust of dispersion ,",0,0,"2100gp"
53,54,"","Enemy spirit pouch ,",0,0,"2100gp"
55,56,"","Dragon's draught (black) ,",0,0,"2300gp"
57,58,"","Dragon's draught (copper) ,",0,0,"2400gp"
59,60,"","Moonfire salve ,",0,0,"2500gp"
61,62,"","Headband of the binder ,",0,0,"2600gp"
63,64,"","Bird feather headdress ,",0,0,"2900gp"
65,66,"","Instrument of the bards (Mac-Fuirmidth Cittern) ,",0,0,"2900gp"
67,68,"","Necklace of nature's teeth ,",0,0,"2900gp"
69,70,"","Troll gut rope ,",0,0,"3000gp"
71,71,"","Dragon's draught (bronze) ,",0,0,"3500gp"
72,72,"","Dragon's draught (green) ,",0,0,"3500gp"
73,73,"","Mithral bells ,",0,0,"3700gp"
74,74,"","Dragonskull talisman ,",0,0,"4000gp"
75,75,"","Wilding clasp ,",0,0,"4000gp"
76,76,"","Methild's harp ,",0,0,"4100gp"
77,77,"","Arvoreen's amuet of aid ,",0,0,"4320gp"
78,78,"","Necklace of lightning ,",0,0,"4350gp"
79,79,"","Dragon's draught (blue) ,",0,0,"4500gp"
80,80,"","Torque of the goddess +1 ,",0,0,"4500gp"
81,81,"","Dragon's draught (silver) ,",0,0,"4600gp"
82,82,"","Ice necklace of the Ulutiun ,",0,0,"5000gp"
83,83,"","Rhingalade's harp ,",0,0,"5400gp"
84,84,"","Dragon's draught (red) ,",0,0,"5500gp"
85,85,"","Dragon's draught (gold) ,",0,0,"5600gp"
86,86,"","Spice jar ,",0,0,"5600gp"
87,87,"","Joyous star song ,",0,0,"5800gp"
88,88,"","Gwaeron's boots ,",0,0,"6000gp"
89,89,"","Cape of the fire bath ,",0,0,"6200gp"
90,90,"","Cape of winter ,",0,0,"6200gp"
91,91,"","Shaundakul's boots ,",0,0,"6300gp"
92,92,"","Elixir of Horus-Re ,",0,0,"6500gp"
93,93,"","Esheen's harp ,",0,0,"6800gp"
94,94,"","Aquamarine of spell extending ,",0,0,"7200gp"
95,95,"","Armband of maximized healing ,",0,0,"7200gp"
96,96,"","Kiira ,",0,0,"7500gp"
97,97,"","Lenses of darkness ,",0,0,"7700gp"
98,98,"","Blast globe ,",0,0,"8000gp"
99,99,"","Gloves of lightning ,",0,0,"8000gp"
100,100,"","Harper pin (lesser) ,",0,0,"8000gp"